# vim: tabstop=3 : shiftwidth=3 : noexpandtab :

###
#====> CONSTANTS
###

Define MOODLE_VAR     "@BASE-DIR@"
Define MOODLE_ROOT    "@SITE-ROOT@"
Define APACHE_MODULES "@APACHE-MODULES@"


###
#====> Host Setup
###

ServerRoot "${MOODLE_VAR}"
Listen     @SITE-PORT@
ServerName @SITE-SERVERNAME@


###
#====> Apache Modules
###

# Core process / security
LoadModule unixd_module "${APACHE_MODULES}/mod_unixd.so"

# MPM event -> needs to be loaded before any other module
LoadModule mpm_event_module "${APACHE_MODULES}/mod_mpm_event.so"

# auth / access control
LoadModule authz_core_module "${APACHE_MODULES}/mod_authz_core.so"
# logging
LoadModule log_config_module "${APACHE_MODULES}/mod_log_config.so"

# proxy / PHP-FPM
LoadModule proxy_module      "${APACHE_MODULES}/mod_proxy.so"
LoadModule proxy_fcgi_module "${APACHE_MODULES}/mod_proxy_fcgi.so"

# moodle necesita rewrite
LoadModule rewrite_module "${APACHE_MODULES}/mod_rewrite.so"

# to handle directories
LoadModule dir_module "${APACHE_MODULES}/mod_dir.so"



###
#====> Directory default index
###

DirectoryIndex index.php index.html index.xhtml index.htm



###
#====> Moodle desde nixpkgs
###

DocumentRoot "${MOODLE_ROOT}"

<Directory "${MOODLE_ROOT}">
	Options       FollowSymlinks
	AllowOverride All
	Require       all granted
</Directory>


###
#====> PHP handling via PHP-FPM
###

<FilesMatch \.php$>
    SetHandler "proxy:fcgi://127.0.0.1:9000"
</FilesMatch>


###
#====> Logs & Runtime files
###

ErrorLog  "${MOODLE_VAR}/logs/apache-error.log"
CustomLog "${MOODLE_VAR}/logs/apache-access.log" combined

PidFile "${MOODLE_VAR}/run/apache.pid"

